### ISSUE TITLE
Unable toauto change theme

### ISSUE THREAD

**Issue by yunchong-song** [g1eny0ung/logseq-github-theme#3]
Hi, this is really a nice theme! I love this theme with VSCode, thanks very much for taking it to Logseq. However, I found that it can not change theme between GitHub Light theme and GitHub Dark theme automatically with system's appearance changing, Logseq version 0.6.5, plug-in version 1.0.0.
Please tell me if I'm wrong in some settings or it's a bug, hope you can fix it! We really love GitHub theme🥳

**Comment by yunchong-song** [comment]
https://user-images.githubusercontent.com/57980447/161183792-fdcabece-a9b4-4efd-94e9-19aa6282bfcb.mp4

**Comment by g1eny0ung** [comment]
Yep, because I'm not putting them all in one file. Currently, Logseq only permits the user to choose only one CSS file, which means the theme developer must write light and dark themes in one file. You can refer to this issue I created: https://github.com/logseq/logseq/issues/4619.

But Logseq will ask the theme to specify a mode (light/dark)... so this is confusing. This is why I divided them into different files.

I'm already drafting a PR (https://github.com/logseq/logseq/pull/4741) to aim to improve this. But I'll still create `GitHub-Light-Dark` and `GitHub-Light-Dark-Dimmed` for backward compatibility.

**Comment by yunchong-song** [comment]
OK, thanks, waiting for `GitHub-Light-Dark` update!

**Comment by g1eny0ung** [comment]
Done in [cb9b2f1](https://github.com/g1eny0ung/logseq-github-theme/commit/cb9b2f14bc7fd24205a3e5d215012d85ad2e01fd).
